### PR TITLE
refactoring for yap + drying up

### PR DESCRIPTION
**Pull request by dgershman**

### CODE REVIEW

**Comment by dgershman** [comment]
#2

**Comment by dgershman** [comment]
@pjaudiomv after the next release of the root server is tagged you should point the root server version to use the same method that yap is using to grab the version number.

**Comment by pjaudiomv** [comment]
cool this looks good to me, thanks! Basic and drupal will probably have to get changed once we figure out releases for those. im guessing maybe use travis for those as well?

**Comment by dgershman** [comment]
yeah i'm sure about how drupal expects it's artifacts.  Can you provide some guidance on that on https://github.com/bmlt-enabled/bmlt-drupal/pull/2

**Comment by dgershman** [comment]
will you be submitting this to the directory?

**Comment by pjaudiomv** [comment]
on wordpress.com? or updating on bmlt.app

**Comment by dgershman** [comment]
both

**Comment by pjaudiomv** [comment]
I tried submitting it on wordpress.com and they shut it down, I then had an couple emails back and forth trying to get them to change their decision. i could forward you email thread if your bored ha. this was his final response and i gave up

 read your explanation a couple times but ... none of that really makes sense when we look at what the plugin does.

It makes a shortcode to list your products for people to download zips. That's.... it.

Even if you made this as an admin only plugin that alerted people to when updates were needed, we would have issues on a different side, as we don't allow that service to be hosted here.

It would make more sense, and be less maintenance for you, to just have people link to https://bmlt.app/what-is-the-bmlt/get-bmlt/download/ instead of self hosting code that reproduces that page. It's better for your SEO as well, which means if someone googles for your software, they get the right site with the latest info.


amnd yea ill update plugin on bmlt.app now

**Comment by dgershman** [comment]
Yeah I guess I wasn’t aware of that.  Just looking to get it update on bmlt.app then.

**Comment by pjaudiomv** [comment]
cool all updated

**Pull request merged**
